# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23847bdfbfabc340a0551b72365fe7652e07d1ee874889a6ca1e6d47e0f0e06f07db687d2f08c3c17653f2973c9994e1e860c4adfdca0242e3b70005dbc5ef86

test:
  secret_key_base: 90c6a4d6fcd95c94eca9fedf5cc8453fd9a438b196a57b450f3a6b7b3a0f966f2d00b087b91451458b2a2df63d1d5a515e91e0cc23529ad0db416edbff394049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
